CREATE TABLE DIRECCION(
IDDIRECCION NCHAR(7) NOT NULL CONSTRAINT PK_IDDIRECCION PRIMARY KEY,
LOCALIDAD NVARCHAR2(50) NOT NULL,
DIRECCION NVARCHAR2(50) NOT NULL
);

CREATE TABLE USUARIO(
IDUSUARIO CHAR(10) NOT NULL CONSTRAINT PK_IDUSUARIO PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
FECHA_NACIMIENTO VARCHAR2(50) NOT NULL,
SEXO CHAR(1) CONSTRAINT CH_SEXO CHECK(SEXO IN ('M','F')),
CORREO VARCHAR2(50) NOT NULL,
CELULAR VARCHAR2(50) NOT NULL

);

ALTER TABLE  USUARIO
ADD DIRECCION NCHAR(7);

DESCRIBE USUARIO;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_DIRECCION FOREIGN KEY (DIRECCION)
REFERENCES DIRECCION (IDDIRECCION);

  
CREATE TABLE VENTA(
IDVENTA CHAR(10) NOT NULL CONSTRAINT PK_IDVENTA PRIMARY KEY,
PRECIO_TOTAL VARCHAR2(50) NOT NULL,
CANTIDAD_TOTAL VARCHAR2(50) NOT NULL,
FECHA_COMPRA VARCHAR2(50) NOT NULL
);

CREATE TABLE DETALLE_VENTA(
IDDETALLE CHAR(10) NOT NULL CONSTRAINT PK_IDDETALLE PRIMARY KEY,
CANTIDAD VARCHAR2(50) NOT NULL,
PRECIO VARCHAR2(50) NOT NULL
);

ALTER TABLE  DETALLE_VENTA
ADD VENTA CHAR(10)
ADD PRODUCTO CHAR(10);


DESCRIBE DETALLE_VENTA;


ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_VENTA FOREIGN KEY (VENTA)
REFERENCES VENTA (IDVENTA);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (PRODUCTO)
REFERENCES PRODUCTO (IDPRODUCTO);

CREATE TABLE PRODUCTO(
IDPRODUCTO CHAR(10) NOT NULL CONSTRAINT PK_IDPRODUCTO PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR2(50) NOT NULL,
PRECIO VARCHAR2(50) NOT NULL,
STOCK VARCHAR2(50) NOT NULL
);

ALTER TABLE  PRODUCTO
ADD TIPO_PRODUCTO CHAR(10);

DESCRIBE PRODUCTO;

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_TIPO_PRODUCTO FOREIGN KEY (TIPO_PRODUCTO)
REFERENCES TIPO_PRODUCTO (IDTIPO);

CREATE TABLE TIPO_PRODUCTO(
IDTIPO CHAR(10) NOT NULL CONSTRAINT PK_IDTIPO PRIMARY KEY,
CATEGORIA VARCHAR2(50) NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL
);

CREATE TABLE REGISTRO(
IDREGISTRO CHAR(10) NOT NULL CONSTRAINT PK_IDREGISTRO PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
CORREO VARCHAR2(50) NOT NULL,
CELULAR VARCHAR2(50) NOT NULL

);
ALTER TABLE  REGISTRO
ADD USUARIO VARCHAR2(50) NOT NULL
ADD CONTRASEÑA VARCHAR2(50) NOT NULL;

DESCRIBE REGISTRO;
